version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
      - DB_USERNAME=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_DATABASE=$POSTGRESDB_DATABASE
    stdin_open: true
    tty: true
  client:
    depends_on:
      - app
    build: ./client
    restart: unless-stopped
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_LOCAL_PORT
    stdin_open: true
    tty: true

volumes:
  db: